"""Seed experiences and services into the database."""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.database import SessionLocal
from app.models.listing import Listing, ListingImage
from app.models.user import User

EXPERIENCES = [
    {
        "title": "Carve marble with a third-generation sculptor",
        "description": "Join master sculptor Dimitris, a third-generation artisan, in his family workshop in the heart of Athens. You'll learn the ancient art of marble carving using traditional tools, creating your own small sculpture to take home. The workshop has been in the family since 1948, and Dimitris will share stories of Greek sculptural traditions while guiding your hands. All materials and tools are provided, along with a refreshing Greek coffee break.",
        "property_type": "experience",
        "location": "Athens, Greece",
        "city": "Athens",
        "country": "Greece",
        "price_per_night": 6595,
        "max_guests": 6,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 5.0,
        "review_count": 142,
        "is_original": True,
        "image_url": "https://picsum.photos/seed/marble/800/800",
    },
    {
        "title": "Art Walking Tour in San Miguel de Allende",
        "description": "Explore the vibrant art scene of San Miguel de Allende on this curated walking tour. Visit hidden galleries, meet local artists in their studios, and discover the colorful street art that makes this UNESCO World Heritage city a creative haven. The tour covers the historic center and includes tastings at a local mezcalería. Perfect for art lovers and culture enthusiasts.",
        "property_type": "experience",
        "location": "San Miguel de Allende, Mexico",
        "city": "San Miguel de Allende",
        "country": "Mexico",
        "price_per_night": 3744,
        "max_guests": 10,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.95,
        "review_count": 87,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&h=800&fit=crop",
    },
    {
        "title": "Sky Garden Early Access with Pastry & Drink",
        "description": "Beat the crowds with exclusive early morning access to London's iconic Sky Garden, 35 floors above the city. Enjoy panoramic views of the Thames, Tower Bridge, and the Shard while sipping artisan coffee and savoring freshly baked pastries. A knowledgeable local guide will point out hidden landmarks and share fascinating stories about London's skyline. The experience lasts about 90 minutes.",
        "property_type": "experience",
        "location": "Greater London, United Kingdom",
        "city": "London",
        "country": "United Kingdom",
        "price_per_night": 1667,
        "max_guests": 12,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.8,
        "review_count": 234,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=800&fit=crop",
    },
    {
        "title": "Savor Premium Matcha in a tea ceremony in Shibuya",
        "description": "Immerse yourself in the meditative art of Japanese tea ceremony in a tranquil tatami room hidden away in bustling Shibuya. Tea master Yuki will guide you through the precise, graceful movements of chanoyu, using ceremonial-grade matcha sourced from Uji. You'll learn the philosophy of ichigo ichie (one time, one meeting) and enjoy traditional wagashi sweets. Kimono rental is available.",
        "property_type": "experience",
        "location": "Shibuya, Tokyo, Japan",
        "city": "Tokyo",
        "country": "Japan",
        "price_per_night": 3591,
        "max_guests": 4,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 5.0,
        "review_count": 198,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1545048702-79362596cdc9?w=800&h=800&fit=crop",
    },
    {
        "title": "Learn pot painting with natural cochinilla dye",
        "description": "Discover the ancient Oaxacan tradition of using cochinilla (cochineal) insects to create vibrant natural dyes. In this hands-on workshop in LA's Arts District, Mexican-American artist Sofia will teach you to extract the vivid crimson pigment and use it to paint beautiful designs on traditional clay pots. Take home your painted pot and a small vial of natural dye.",
        "property_type": "experience",
        "location": "Los Angeles, United States",
        "city": "Los Angeles",
        "country": "United States",
        "price_per_night": 4767,
        "max_guests": 8,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.98,
        "review_count": 56,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&h=800&fit=crop",
    },
    {
        "title": "Sunset Sailing & Wine Tasting in Santorini",
        "description": "Set sail on a traditional wooden caïque along the Santorini caldera as the sun paints the sky in stunning shades of gold and rose. Your captain and sommelier will pair local Assyrtiko wines with fresh Mediterranean mezze while you take in views of the volcanic cliffs, hot springs, and whitewashed villages. Includes swimming stops at secluded coves.",
        "property_type": "experience",
        "location": "Santorini, Greece",
        "city": "Santorini",
        "country": "Greece",
        "price_per_night": 8900,
        "max_guests": 8,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.97,
        "review_count": 312,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&h=800&fit=crop",
    },
    {
        "title": "Secret Street Food Tour in Bangkok",
        "description": "Go beyond the tourist trail with local food writer Nong on this evening street food adventure through Bangkok's hidden alleyways. Visit 7 hand-picked stalls serving dishes you won't find in any guidebook — from smoky charcoal-grilled satay to silky boat noodles and the city's best mango sticky rice. Includes all tastings and a tuk-tuk ride.",
        "property_type": "experience",
        "location": "Bangkok, Thailand",
        "city": "Bangkok",
        "country": "Thailand",
        "price_per_night": 2800,
        "max_guests": 6,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.99,
        "review_count": 445,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=800&fit=crop",
    },
    {
        "title": "Flamenco Dance Masterclass in Seville",
        "description": "Feel the duende — the soul of flamenco — in a private studio in Seville's historic Triana district. Professional dancer Carmen will teach you the foundational footwork, hand movements, and emotional expression of this passionate art form. The class is suitable for all levels and ends with a mini performance. Includes a glass of sherry.",
        "property_type": "experience",
        "location": "Seville, Spain",
        "city": "Seville",
        "country": "Spain",
        "price_per_night": 5200,
        "max_guests": 8,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.96,
        "review_count": 178,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1535525153412-5a42439a210d?w=800&h=800&fit=crop",
    },
    {
        "title": "Northern Lights Photography in Tromsø",
        "description": "Chase the aurora borealis with an expert photographer in the Arctic wilderness around Tromsø. You'll learn long-exposure techniques, camera settings for night sky photography, and how to compose stunning Northern Lights images. Warm Arctic gear, hot chocolate, and traditional Norwegian snacks are provided. Images guaranteed or a free re-booking.",
        "property_type": "experience",
        "location": "Tromsø, Norway",
        "city": "Tromsø",
        "country": "Norway",
        "price_per_night": 12500,
        "max_guests": 6,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.93,
        "review_count": 89,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=800&h=800&fit=crop",
    },
    {
        "title": "Farm-to-Table Cooking in Tuscany",
        "description": "Spend a magical morning at an organic Tuscan farmhouse. Start by foraging herbs and picking vegetables from the garden, then join nonna Maria in her farmhouse kitchen to prepare a traditional four-course meal. Learn to make fresh pasta by hand, wood-fired focaccia, and authentic ragù. End with a feast at the long farmhouse table with estate wines.",
        "property_type": "experience",
        "location": "Chianti, Tuscany, Italy",
        "city": "Florence",
        "country": "Italy",
        "price_per_night": 7800,
        "max_guests": 8,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.99,
        "review_count": 267,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=800&fit=crop",
    },
    {
        "title": "Surf Lesson & Beach Yoga in Bali",
        "description": "Start your Bali morning with a rejuvenating sunrise yoga session on the beach at Canggu, followed by a surf lesson with certified instructors on beginner-friendly waves. All equipment is provided, and the session includes a smoothie bowl at a beachfront café. Perfect for solo travelers, couples, and anyone seeking a blissful start to the day.",
        "property_type": "experience",
        "location": "Canggu, Bali, Indonesia",
        "city": "Bali",
        "country": "Indonesia",
        "price_per_night": 3200,
        "max_guests": 10,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.94,
        "review_count": 156,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1528150177508-7cc0c36cda5c?w=800&h=800&fit=crop",
    },
    {
        "title": "Jazz & Blues Night Walk in New Orleans",
        "description": "Discover the birthplace of jazz on this atmospheric evening walking tour through the French Quarter and Frenchmen Street. Visit legendary jazz clubs, hear stories of Louis Armstrong and Buddy Bolden, and enjoy live performances at intimate venues. Includes two drink tokens and a local praline treat.",
        "property_type": "experience",
        "location": "New Orleans, United States",
        "city": "New Orleans",
        "country": "United States",
        "price_per_night": 4100,
        "max_guests": 12,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.92,
        "review_count": 201,
        "is_original": True,
        "image_url": "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&h=800&fit=crop",
    },
]

SERVICES = [
    {
        "title": "New Delhi photo session by a Female Photographer",
        "description": "Capture your memories in New Delhi with a professional female photographer. Whether it's a solo travel portrait session at India Gate, a couples shoot at Humayun's Tomb, or family photos at Lodhi Gardens, you'll get stunning, magazine-quality images. Includes 1 hour of shooting, 30+ edited high-res digital photos, and a private online gallery.",
        "property_type": "service",
        "location": "New Delhi, India",
        "city": "New Delhi",
        "country": "India",
        "price_per_night": 8500,
        "max_guests": 1,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 5.0,
        "review_count": 64,
        "is_popular": True,
        "image_url": "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=800&h=800&fit=crop",
    },
    {
        "title": "Makeup artistry by Sukoon",
        "description": "Get event-ready with professional makeup artist Sukoon, who specializes in bridal, party, and editorial looks. Using premium products from MAC, Bobbi Brown, and Fenty Beauty, Sukoon will create a customized look that enhances your natural beauty. Service includes consultation, skin prep, full face makeup, and touch-up kit. Available for travel to your hotel or venue.",
        "property_type": "service",
        "location": "Mumbai, India",
        "city": "Mumbai",
        "country": "India",
        "price_per_night": 2000,
        "max_guests": 1,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 5.0,
        "review_count": 38,
        "is_popular": False,
        "image_url": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&h=800&fit=crop",
    },
    {
        "title": "Historical photo shoot by Madhur",
        "description": "Work with acclaimed photographer Madhur to create stunning portraits at Jaipur's most photogenic locations — Hawa Mahal, Amber Fort, and the Pink City's colorful streets. Madhur's editorial style blends fashion photography with documentary storytelling. Package includes 2 hours of shooting, 50+ edited images, and an Instagram highlight reel.",
        "property_type": "service",
        "location": "Jaipur, India",
        "city": "Jaipur",
        "country": "India",
        "price_per_night": 10000,
        "max_guests": 1,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.91,
        "review_count": 22,
        "is_popular": False,
        "image_url": "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=800&fit=crop",
    },
    {
        "title": "Strength and mobility sessions by Mayank",
        "description": "Certified personal trainer Mayank offers customized strength and mobility sessions at your accommodation or a nearby park. Whether you want to maintain your fitness routine while traveling, work on flexibility, or try something new, Mayank adapts each session to your goals and fitness level. Equipment provided. Minimum ₹3,600 to book (2 sessions).",
        "property_type": "service",
        "location": "Bangalore, India",
        "city": "Bangalore",
        "country": "India",
        "price_per_night": 1800,
        "max_guests": 1,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 5.0,
        "review_count": 15,
        "is_popular": False,
        "image_url": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop",
    },
    {
        "title": "Bridal and party looks by Nirmala",
        "description": "Professional makeup and hairstyling services for weddings, engagements, and special occasions. Nirmala specializes in South Indian bridal looks, blending traditional aesthetics with modern trends. She uses only cruelty-free, premium products. Service includes trial session, day-of makeup and hair, and touch-up visits. Travel to venue included within city limits.",
        "property_type": "service",
        "location": "Chennai, India",
        "city": "Chennai",
        "country": "India",
        "price_per_night": 2500,
        "max_guests": 1,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.85,
        "review_count": 8,
        "is_popular": False,
        "image_url": "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&h=800&fit=crop",
    },
    {
        "title": "Occasion ready looks by Happy",
        "description": "Stylist Happy brings the salon to you! Specializing in cocktail party, festive, and date-night looks, Happy offers full makeup and hair styling at your hotel or Airbnb. From bold glamour to soft elegance, she tailors every look to your outfit and vibe. Includes consultation, full face, hairstyling, and a mini touch-up kit.",
        "property_type": "service",
        "location": "Hyderabad, India",
        "city": "Hyderabad",
        "country": "India",
        "price_per_night": 4000,
        "max_guests": 1,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.90,
        "review_count": 5,
        "is_popular": False,
        "image_url": "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&h=800&fit=crop",
    },
    {
        "title": "Private yoga session by Ananya",
        "description": "Start your day with a private yoga and meditation session led by certified instructor Ananya. Choose between Hatha, Vinyasa, or Yin yoga, tailored to your level. Sessions can be held at your accommodation, a rooftop, or a local park. Includes breathing exercises, guided meditation, and personalized stretching routine. Mats and props provided.",
        "property_type": "service",
        "location": "Goa, India",
        "city": "Goa",
        "country": "India",
        "price_per_night": 3000,
        "max_guests": 4,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.97,
        "review_count": 44,
        "is_popular": True,
        "image_url": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=800&fit=crop",
    },
    {
        "title": "City tour & photography by Arjun",
        "description": "Explore the best of Kolkata with photographer-guide Arjun. This half-day tour covers Howrah Bridge, Kumartuli, College Street, and the flower market, with Arjun capturing candid, professional photos of you along the way. You'll receive 40+ edited images within 48 hours. A perfect blend of sightseeing and photo memories.",
        "property_type": "service",
        "location": "Kolkata, India",
        "city": "Kolkata",
        "country": "India",
        "price_per_night": 6000,
        "max_guests": 4,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.95,
        "review_count": 31,
        "is_popular": False,
        "image_url": "https://images.unsplash.com/photo-1558431382-27e303142255?w=800&h=800&fit=crop",
    },
    {
        "title": "Ayurvedic wellness consultation by Dr. Priya",
        "description": "Consult with Dr. Priya, a certified Ayurvedic practitioner with 15 years of experience. She'll assess your dosha (body constitution), recommend personalized dietary and lifestyle changes, and guide you through a therapeutic oil massage technique. Includes a take-home wellness kit with herbal supplements and a personalized routine card.",
        "property_type": "service",
        "location": "Kerala, India",
        "city": "Kochi",
        "country": "India",
        "price_per_night": 5500,
        "max_guests": 1,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.98,
        "review_count": 52,
        "is_popular": True,
        "image_url": "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800&h=800&fit=crop",
    },
    {
        "title": "Henna art session by Meera",
        "description": "Get beautiful, intricate henna designs applied by award-winning henna artist Meera. Choose from traditional Rajasthani, Arabic, or contemporary fusion styles. Perfect for weddings, festivals, or just because. Meera uses 100% natural, organic henna paste. Session includes design consultation and aftercare tips for lasting color.",
        "property_type": "service",
        "location": "Udaipur, India",
        "city": "Udaipur",
        "country": "India",
        "price_per_night": 1500,
        "max_guests": 4,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.96,
        "review_count": 72,
        "is_popular": False,
        "image_url": "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800&h=800&fit=crop",
    },
    {
        "title": "Professional videography by Rohan",
        "description": "Capture your travel memories in cinematic style with professional videographer Rohan. Using professional-grade equipment, Rohan creates beautifully edited 3-5 minute travel highlight reels. Available for couples, families, and solo travelers. Includes 3 hours of filming, drone footage (where permitted), background music, and color-graded delivery within 72 hours.",
        "property_type": "service",
        "location": "Jaipur, India",
        "city": "Jaipur",
        "country": "India",
        "price_per_night": 15000,
        "max_guests": 6,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 4.88,
        "review_count": 19,
        "is_popular": False,
        "image_url": "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&h=800&fit=crop",
    },
    {
        "title": "Traditional cooking class by Lakshmi",
        "description": "Learn to cook authentic South Indian cuisine with home chef Lakshmi in her cozy Mylapore kitchen. The 3-hour class covers dosa batter, sambar, coconut chutney, and a signature dessert. All ingredients are fresh and locally sourced. You'll leave with printed recipes and a spice pack to recreate the dishes at home. Vegetarian menu.",
        "property_type": "service",
        "location": "Chennai, India",
        "city": "Chennai",
        "country": "India",
        "price_per_night": 2800,
        "max_guests": 6,
        "bedrooms": 0,
        "beds": 0,
        "bathrooms": 0,
        "rating": 5.0,
        "review_count": 41,
        "is_popular": True,
        "image_url": "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&h=800&fit=crop",
    },
]


def seed():
    db = SessionLocal()
    
    # Get a host user to assign these to
    host = db.query(User).filter(User.role == "host").first()
    if not host:
        print("ERROR: No host user found. Please seed users first.")
        db.close()
        return
    
    print(f"Using host: {host.name} (id={host.id})")
    
    # Check if experiences already exist
    existing_exp = db.query(Listing).filter(Listing.property_type == "experience").count()
    existing_svc = db.query(Listing).filter(Listing.property_type == "service").count()
    
    if existing_exp > 0:
        print(f"⚠ {existing_exp} experiences already exist. Skipping experience seeding.")
    else:
        for exp in EXPERIENCES:
            image_url = exp.pop("image_url")
            listing = Listing(host_id=host.id, **exp)
            db.add(listing)
            db.flush()
            db.add(ListingImage(listing_id=listing.id, image_url=image_url, display_order=0))
            print(f"  ✅ Experience: {listing.title}")
        print(f"Seeded {len(EXPERIENCES)} experiences.")
    
    if existing_svc > 0:
        print(f"⚠ {existing_svc} services already exist. Skipping service seeding.")
    else:
        for svc in SERVICES:
            image_url = svc.pop("image_url")
            listing = Listing(host_id=host.id, **svc)
            db.add(listing)
            db.flush()
            db.add(ListingImage(listing_id=listing.id, image_url=image_url, display_order=0))
            print(f"  ✅ Service: {listing.title}")
        print(f"Seeded {len(SERVICES)} services.")
    
    db.commit()
    db.close()
    print("Done!")


if __name__ == "__main__":
    seed()
