export const mockExperiences = [
  {
    id: 1,
    title: "Carve marble with a third-generation sculptor",
    location: "Athens, Greece",
    price: "₹6,595",
    rating: 5.0,
    imageUrl: "https://picsum.photos/seed/exp1/800/1000",
    isOriginal: true,
  },
  {
    id: 2,
    title: "Art Walking Tour in San Miguel de Allende",
    location: "San Miguel de Allende, Mexico",
    price: "₹3,744",
    rating: 4.95,
    imageUrl: "https://picsum.photos/seed/exp2/800/1000",
    isOriginal: true,
  },
  {
    id: 3,
    title: "Sky Garden Early Access Ticket with Pastry & Drink",
    location: "Greater London, United Kingdom",
    price: "₹1,667",
    rating: 4.8,
    imageUrl: "https://picsum.photos/seed/exp3/800/1000",
    isOriginal: true,
  },
  {
    id: 4,
    title: "Savor Premium Matcha in a tea ceremony in Shibuya",
    location: "Shibuya, Japan",
    price: "₹3,591",
    rating: 5.0,
    imageUrl: "https://picsum.photos/seed/exp4/800/1000",
    isOriginal: true,
  },
  {
    id: 5,
    title: "Learn pot painting with natural cochinilla dye",
    location: "Los Angeles, United States",
    price: "₹4,767",
    rating: 4.98,
    imageUrl: "https://picsum.photos/seed/exp5/800/1000",
    isOriginal: true,
  },
];

export const mockServices = [
  {
    id: 1,
    title: "New Delhi photo session by a Female Photographer",
    price: "₹8,500",
    rating: 5.0,
    imageUrl: "https://picsum.photos/seed/serv1/800/800",
    isPopular: true,
  },
  {
    id: 2,
    title: "Makeup artistry by Sukoon",
    price: "₹2,000",
    rating: 5.0,
    imageUrl: "https://picsum.photos/seed/serv2/800/800",
    isPopular: false,
  },
  {
    id: 3,
    title: "Historical photo shoot by Madhur",
    price: "₹10,000",
    rating: 4.91,
    imageUrl: "https://picsum.photos/seed/serv3/800/800",
    isPopular: false,
  },
  {
    id: 4,
    title: "Strength and mobility sessions by Mayank",
    price: "₹1,800",
    rating: 5.0,
    minBooking: "Minimum ₹3,600 to book",
    imageUrl: "https://picsum.photos/seed/serv4/800/800",
    isPopular: false,
  },
  {
    id: 5,
    title: "Bridal and party looks by Nirmala",
    price: "₹2,500",
    rating: null,
    imageUrl: "https://picsum.photos/seed/serv5/800/800",
    isPopular: false,
  },
  {
    id: 6,
    title: "Occasion ready looks by Happy",
    price: "₹4,000",
    rating: null,
    imageUrl: "https://picsum.photos/seed/serv6/800/800",
    isPopular: false,
  }
];
